name: Terraform Deploy Template

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      TF_GITHUB_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Configure Git credentials for private modules
        env:
          TF_GITHUB_PAT: ${{ secrets.TF_GITHUB_PAT }}
        run: |
          git config --global url."https://${TF_GITHUB_PAT}@github.com/".insteadOf "https://github.com/"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
